version: "3"

services:

  web:

    image: nginx:bullseye

    volumes:

      - ./src:/usr/share/nginx/html
      - data-volume:/app/data
    
    ports:

      - "8080:80"

volumes:

  data-volume:


