version: '3'

services:

  react-app:
    build:
      context: ./front/task-manager
      dockerfile: Dockerfile
    image: react-app
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
      - springboot-restful-webservices



  mysql-db:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tasks_generator
    ports:
      - "3307:3306"
    networks:
      springboot-mysql-net:

  springboot-restful-webservices:
    container_name: springboot-restful-webservices
    build:
      context: ./back/docker/TaskGenerator/
      dockerfile: Dockerfile
    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: root 
      MYSQL_PASSWORD: root   
      MYSQL_PORT: 3306
    ports:
      - "8080:8080"
    depends_on:
      - mysql-db
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net:



