version: "3"
networks:
  mi-red:
services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "86:80"
    networks:
      - mi-red
